spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

server:
  port: 8088
#  ssl:
#    key-store: classpath:www.qingheli.tech.jks
#    key-store-password: phifbs4s
#    keyStoreType: JKS

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
